# Default values for Health Check
imageOrg: "drycc"
imagePullPolicy: "Always"
imageTag: "canary"
imageRegistry: "docker.io"
# imagePullSecrets pre-existing secrets to use to pull images from a private registry
imagePullSecrets: []
rbacApiVersion: rbac.authorization.k8s.io/v1
