apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusterserviceclasses.servicecatalog.k8s.io
  labels:
    svcat: "true"
spec:
  group: servicecatalog.k8s.io
  scope: Cluster
  names:
    plural: clusterserviceclasses
    singular: clusterserviceclass
    kind: ClusterServiceClass
    # categories is a list of grouped resources the custom resource belongs to.
    categories:
      - all
      - svcat
  versions:
    - additionalPrinterColumns:
      - name: External-Name
        type: string
        jsonPath: .spec.externalName
      - name: Broker
        type: string
        jsonPath: .spec.clusterServiceBrokerName
      - name: Age
        type: date
        jsonPath: .metadata.creationTimestamp
      name: v1beta1
      served: true
      storage: true
      subresources:
        status: {}
