apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusterservicebrokers.servicecatalog.k8s.io
  labels:
    svcat: "true"
spec:
  group: servicecatalog.k8s.io
  scope: Cluster
  names:
    plural: clusterservicebrokers
    singular: clusterservicebroker
    kind: ClusterServiceBroker
    # categories is a list of grouped resources the custom resource belongs to.
    categories:
      - all
      - svcat
  versions:
    - additionalPrinterColumns:
      - name: URL
        type: string
        jsonPath: .spec.url
      - name: Status
        type: string
        jsonPath: .status.lastConditionState
      - name: Age
        type: date
        jsonPath: .metadata.creationTimestamp
      name: v1beta1
      served: true
      storage: true
      subresources:
        status: {}
