apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: serviceplans.servicecatalog.k8s.io
  labels:
    svcat: "true"
spec:
  group: servicecatalog.k8s.io
  scope: Namespaced
  names:
    plural: serviceplans
    singular: serviceplan
    kind: ServicePlan
    # categories is a list of grouped resources the custom resource belongs to.
    categories:
      - all
      - svcat
  versions:
    - additionalPrinterColumns:
      - name: External-Name
        type: string
        jsonPath: .spec.externalName
      - name: Broker
        type: string
        jsonPath: .spec.serviceBrokerName
      - name: Class
        type: string
        jsonPath: .spec.serviceClassRef.name
      - name: Age
        type: date
        jsonPath: .metadata.creationTimestamp
      name: v1beta1
      served: true
      storage: true
      subresources:
        status: {}
