/*
Copyright 2025 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

import (
	servicecatalogv1beta1 "github.com/drycc-addons/service-catalog/pkg/apis/servicecatalog/v1beta1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// ClusterServicePlanLister helps list ClusterServicePlans.
// All objects returned here must be treated as read-only.
type ClusterServicePlanLister interface {
	// List lists all ClusterServicePlans in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*servicecatalogv1beta1.ClusterServicePlan, err error)
	// Get retrieves the ClusterServicePlan from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*servicecatalogv1beta1.ClusterServicePlan, error)
	ClusterServicePlanListerExpansion
}

// clusterServicePlanLister implements the ClusterServicePlanLister interface.
type clusterServicePlanLister struct {
	listers.ResourceIndexer[*servicecatalogv1beta1.ClusterServicePlan]
}

// NewClusterServicePlanLister returns a new ClusterServicePlanLister.
func NewClusterServicePlanLister(indexer cache.Indexer) ClusterServicePlanLister {
	return &clusterServicePlanLister{listers.New[*servicecatalogv1beta1.ClusterServicePlan](indexer, servicecatalogv1beta1.Resource("clusterserviceplan"))}
}
