/*
Copyright 2025 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	context "context"

	servicecatalogv1beta1 "github.com/drycc-addons/service-catalog/pkg/apis/servicecatalog/v1beta1"
	scheme "github.com/drycc-addons/service-catalog/pkg/client/clientset_generated/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ClusterServiceBrokersGetter has a method to return a ClusterServiceBrokerInterface.
// A group's client should implement this interface.
type ClusterServiceBrokersGetter interface {
	ClusterServiceBrokers() ClusterServiceBrokerInterface
}

// ClusterServiceBrokerInterface has methods to work with ClusterServiceBroker resources.
type ClusterServiceBrokerInterface interface {
	Create(ctx context.Context, clusterServiceBroker *servicecatalogv1beta1.ClusterServiceBroker, opts v1.CreateOptions) (*servicecatalogv1beta1.ClusterServiceBroker, error)
	Update(ctx context.Context, clusterServiceBroker *servicecatalogv1beta1.ClusterServiceBroker, opts v1.UpdateOptions) (*servicecatalogv1beta1.ClusterServiceBroker, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, clusterServiceBroker *servicecatalogv1beta1.ClusterServiceBroker, opts v1.UpdateOptions) (*servicecatalogv1beta1.ClusterServiceBroker, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*servicecatalogv1beta1.ClusterServiceBroker, error)
	List(ctx context.Context, opts v1.ListOptions) (*servicecatalogv1beta1.ClusterServiceBrokerList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *servicecatalogv1beta1.ClusterServiceBroker, err error)
	ClusterServiceBrokerExpansion
}

// clusterServiceBrokers implements ClusterServiceBrokerInterface
type clusterServiceBrokers struct {
	*gentype.ClientWithList[*servicecatalogv1beta1.ClusterServiceBroker, *servicecatalogv1beta1.ClusterServiceBrokerList]
}

// newClusterServiceBrokers returns a ClusterServiceBrokers
func newClusterServiceBrokers(c *ServicecatalogV1beta1Client) *clusterServiceBrokers {
	return &clusterServiceBrokers{
		gentype.NewClientWithList[*servicecatalogv1beta1.ClusterServiceBroker, *servicecatalogv1beta1.ClusterServiceBrokerList](
			"clusterservicebrokers",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *servicecatalogv1beta1.ClusterServiceBroker {
				return &servicecatalogv1beta1.ClusterServiceBroker{}
			},
			func() *servicecatalogv1beta1.ClusterServiceBrokerList {
				return &servicecatalogv1beta1.ClusterServiceBrokerList{}
			},
		),
	}
}
