/*
Copyright 2025 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	context "context"

	servicecatalogv1beta1 "github.com/drycc-addons/service-catalog/pkg/apis/servicecatalog/v1beta1"
	scheme "github.com/drycc-addons/service-catalog/pkg/client/clientset_generated/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ClusterServiceClassesGetter has a method to return a ClusterServiceClassInterface.
// A group's client should implement this interface.
type ClusterServiceClassesGetter interface {
	ClusterServiceClasses() ClusterServiceClassInterface
}

// ClusterServiceClassInterface has methods to work with ClusterServiceClass resources.
type ClusterServiceClassInterface interface {
	Create(ctx context.Context, clusterServiceClass *servicecatalogv1beta1.ClusterServiceClass, opts v1.CreateOptions) (*servicecatalogv1beta1.ClusterServiceClass, error)
	Update(ctx context.Context, clusterServiceClass *servicecatalogv1beta1.ClusterServiceClass, opts v1.UpdateOptions) (*servicecatalogv1beta1.ClusterServiceClass, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, clusterServiceClass *servicecatalogv1beta1.ClusterServiceClass, opts v1.UpdateOptions) (*servicecatalogv1beta1.ClusterServiceClass, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*servicecatalogv1beta1.ClusterServiceClass, error)
	List(ctx context.Context, opts v1.ListOptions) (*servicecatalogv1beta1.ClusterServiceClassList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *servicecatalogv1beta1.ClusterServiceClass, err error)
	ClusterServiceClassExpansion
}

// clusterServiceClasses implements ClusterServiceClassInterface
type clusterServiceClasses struct {
	*gentype.ClientWithList[*servicecatalogv1beta1.ClusterServiceClass, *servicecatalogv1beta1.ClusterServiceClassList]
}

// newClusterServiceClasses returns a ClusterServiceClasses
func newClusterServiceClasses(c *ServicecatalogV1beta1Client) *clusterServiceClasses {
	return &clusterServiceClasses{
		gentype.NewClientWithList[*servicecatalogv1beta1.ClusterServiceClass, *servicecatalogv1beta1.ClusterServiceClassList](
			"clusterserviceclasses",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *servicecatalogv1beta1.ClusterServiceClass { return &servicecatalogv1beta1.ClusterServiceClass{} },
			func() *servicecatalogv1beta1.ClusterServiceClassList {
				return &servicecatalogv1beta1.ClusterServiceClassList{}
			},
		),
	}
}
