/*
Copyright 2024 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"context"

	v1beta1 "github.com/drycc-addons/service-catalog/pkg/apis/servicecatalog/v1beta1"
	scheme "github.com/drycc-addons/service-catalog/pkg/client/clientset_generated/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ServicePlansGetter has a method to return a ServicePlanInterface.
// A group's client should implement this interface.
type ServicePlansGetter interface {
	ServicePlans(namespace string) ServicePlanInterface
}

// ServicePlanInterface has methods to work with ServicePlan resources.
type ServicePlanInterface interface {
	Create(ctx context.Context, servicePlan *v1beta1.ServicePlan, opts v1.CreateOptions) (*v1beta1.ServicePlan, error)
	Update(ctx context.Context, servicePlan *v1beta1.ServicePlan, opts v1.UpdateOptions) (*v1beta1.ServicePlan, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, servicePlan *v1beta1.ServicePlan, opts v1.UpdateOptions) (*v1beta1.ServicePlan, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta1.ServicePlan, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1beta1.ServicePlanList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.ServicePlan, err error)
	ServicePlanExpansion
}

// servicePlans implements ServicePlanInterface
type servicePlans struct {
	*gentype.ClientWithList[*v1beta1.ServicePlan, *v1beta1.ServicePlanList]
}

// newServicePlans returns a ServicePlans
func newServicePlans(c *ServicecatalogV1beta1Client, namespace string) *servicePlans {
	return &servicePlans{
		gentype.NewClientWithList[*v1beta1.ServicePlan, *v1beta1.ServicePlanList](
			"serviceplans",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1beta1.ServicePlan { return &v1beta1.ServicePlan{} },
			func() *v1beta1.ServicePlanList { return &v1beta1.ServicePlanList{} }),
	}
}
