kind: ServiceAccount
apiVersion: v1
metadata:
  name: migration-job-account
  namespace: {{ .Release.Namespace }}
  labels:
    migration-job: "true"
    app: {{ template "fullname" . }}-migration-job
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: migration-job-account
  labels:
    migration-job: "true"
    app: {{ template "fullname" . }}-migration-job
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs:     ["get", "update"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs:     ["list"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs:     ["get", "update"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs:     ["delete"]
  - apiGroups: ["servicecatalog.k8s.io"]
    resources:
    - "clusterserviceclasses"
    - "clusterserviceplans"
    - "clusterservicebrokers"
    - "serviceinstances"
    - "servicebindings"
    - "serviceclasses"
    - "serviceplans"
    - "servicebrokers"
    verbs: ["list", "get", "create", "patch", "delete"]
  - apiGroups: ["servicecatalog.k8s.io"]
    resources:
    - "clusterservicebrokers/status"
    - "clusterserviceclasses/status"
    - "clusterserviceplans/status"
    - "serviceinstances/status"
    - "serviceinstances"
    - "servicebindings/status"
    - "servicebrokers/status"
    - "serviceclasses/status"
    - "serviceplans/status"
    verbs: ["update"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: migration-job-account
  labels:
    migration-job: "true"
    app: {{ template "fullname" . }}-migration-job
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
subjects:
  - kind: ServiceAccount
    name: migration-job-account
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: migration-job-account

---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "fullname" . }}-migration-job
  labels:
    app: {{ template "fullname" . }}-migration-job
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        {{- if .Values.podLabels }}
        {{- tpl (toYaml .Values.podLabels) $ | nindent 8 }}
        {{- end }}
        migration-job: "true"
        app: {{ template "fullname" . }}-migration-job
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
    spec:
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName | quote }}
      {{- end }}
{{- with .Values.securityContext }}
      securityContext:
{{ toYaml . | indent 8 }}
{{- end }}
      restartPolicy: Never
      serviceAccountName: migration-job-account
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: {{ template "fullname" . }}-migration-storage
      containers:
        - name: job
          image: {{ .Values.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          args:
          - migration
          - --action
          - restore
          - --service-catalog-namespace
          - {{ .Release.Namespace }}
          - --controller-manager-deployment
          - {{ template "fullname" . }}-controller-manager
          - --storage-path=data/
          - --webhook-service-name
          - {{ template "fullname" . }}-webhook
          - --webhook-service-port
          - "{{ .Values.webhook.service.port }}"
          - --pvc-name
          - {{ template "fullname" . }}-migration-storage
          volumeMounts:
          - name: storage
            mountPath: /data
{{- with .Values.affinity }}
      affinity: {{- tpl (toYaml .) $ | nindent 8 }}
{{- end }}
{{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}
