/*
Copyright 2024 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package internalversion

import (
	settings "github.com/drycc-addons/service-catalog/pkg/apis/settings"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/listers"
	"k8s.io/client-go/tools/cache"
)

// PodPresetLister helps list PodPresets.
// All objects returned here must be treated as read-only.
type PodPresetLister interface {
	// List lists all PodPresets in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*settings.PodPreset, err error)
	// PodPresets returns an object that can list and get PodPresets.
	PodPresets(namespace string) PodPresetNamespaceLister
	PodPresetListerExpansion
}

// podPresetLister implements the PodPresetLister interface.
type podPresetLister struct {
	listers.ResourceIndexer[*settings.PodPreset]
}

// NewPodPresetLister returns a new PodPresetLister.
func NewPodPresetLister(indexer cache.Indexer) PodPresetLister {
	return &podPresetLister{listers.New[*settings.PodPreset](indexer, settings.Resource("podpreset"))}
}

// PodPresets returns an object that can list and get PodPresets.
func (s *podPresetLister) PodPresets(namespace string) PodPresetNamespaceLister {
	return podPresetNamespaceLister{listers.NewNamespaced[*settings.PodPreset](s.ResourceIndexer, namespace)}
}

// PodPresetNamespaceLister helps list and get PodPresets.
// All objects returned here must be treated as read-only.
type PodPresetNamespaceLister interface {
	// List lists all PodPresets in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*settings.PodPreset, err error)
	// Get retrieves the PodPreset from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*settings.PodPreset, error)
	PodPresetNamespaceListerExpansion
}

// podPresetNamespaceLister implements the PodPresetNamespaceLister
// interface.
type podPresetNamespaceLister struct {
	listers.ResourceIndexer[*settings.PodPreset]
}
